site_name: Ursoaia Edu Online
site_description: "Ursoaia Edu Online is a platform for online education and learning resources."
site_author: "Ursoaia Edu Team"
site_url: "https://ursoaia-edu.online"
repo_url: "https://github.com/ursoaia-edu/ursoaia-edu.online.git"

theme:
  name: null
  custom_dir: custom_theme

extra:
  status_badge_text: "Currently building"
  status_badge_highlight: "Smart Greenhouse v2"

nav:
  - Home: index.md
  - Guide:
      - Setup: guide/setup.md
  - Projects:
      - Arduino:
          - LED Cube: projects/arduino/led_cube.md
          - Starter Kits: projects/arduino/kits.md
      - ESP32:
          - LED Blink: projects/esp32/led_blink.md
          - Temperature & Humidity: projects/esp32/temperature.md
          - Temperature Web Server: projects/esp32/temperature_web.md
      - LoPy:
          - LoRaWAN Node: projects/lopy/lorawan_node.md
      - Raspberry Pi:
          - Overview: projects/raspberry_pi/index.md
